project:
  type: website

website:
  title: "<img src='/images/meteor_logo.png' alt='Meteor Logo' style='width: 2.7em; height: 2.3em; border-radius: 20%;'> <b> Meteoric Fall: a comet-ment to data</b>"
  navbar:
    right:
      - icon: github
        href: https://info-526-s24.github.io/project-final-VizWizards/
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: lumen
      dark: darkly
    toc: true

execute:
  freeze: auto
